# ssl_robocup_map.yaml
#===============================================================================
# Author: Carl Larsson
# Creation date: -
# Last modified: 2024-11-15 by Carl Larsson
# Description: nav2 stack map parameter file, used by launch file. (DEPRICATED)
# License: See LICENSE file for license details.
#===============================================================================

image: "/home/carl/dev/dva490/robot-controller-interface/config/map/temp_map.pgm"
resolution: 0.050000
origin: [0.000000, 0.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196
